trigger:
  - main

variables:
  - group: WLTP
  - name: vmImageName
    value: 'ubuntu-latest'

steps:
  - checkout: self
    submodules: true
    fetchDepth: 0
  - task: CmdLine@2
    inputs:
      script: |
        git checkout $(Build.SourceBranchName)
        git remote add mbga https://$(MBGA_PAT):@${MBGA_GITHUB_HOST}/WLTP-Frontend//status-page-frontend.git
        git push -u mbga $(Build.SourceBranchName) --tags
