apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sndk7-statuspage-frontend.fullname" . }}
  labels:
    {{- include "sndk7-statuspage-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sndk7-statuspage-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sndk7-statuspage-frontend.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: API_HTTP_URI
              value: "{{ .Values.API_HTTP_URI }}"
            - name: LANGUAGE_HTTP_URI
              value: "{{ .Values.LANGUAGE_HTTP_URI }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: "{{ include "sndk7-statuspage-frontend.fullname" . }}-volume"
          configMap:
            name: {{ include "sndk7-statuspage-frontend.fullname" . }}
