# Default values for sndk7-statuspage-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sndk7images.azurecr.io/sndk7/statuspage-frontend
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  targetPort: 8080
  port: 80

GQL_HTTP_URI: ""
DOWNLOAD_HTTP_URI: ""
LANGUAGE_HTTP_URI: ""
RANGES_WITH_ERROR_LINK: ""
ACTIVATE_ENTITLEMENTS_DEBUG: "false"
SHOW_DEPUTY_FEATURE: "false"
SHOW_SIMULATION_FEATURE: "false"
SHOW_TRACE_FEATURE: "false"
SHOW_CACHE_FEATURE: "false"
SHOW_LIST_RANGE_CALC_FEATURE: "false"
TRACE_URI: ""
CURRENT_SPRINT: ""
TRACE_SERVICE_NAME: ""

ingress:
  enabled: false
  annotations: { }
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: [ ]
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
